# Generated by Django 5.1.1 on 2024-11-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistrypersonalinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='casehistrypersonalinfo',
            name='height',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='casehistrypersonalinfo',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
