# Generated by Django 5.1.1 on 2024-11-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0004_remove_followup_enqid_remove_followup_followedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sourcedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(default=None, max_length=200)),
                ('details', models.CharField(default=None, max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(default=None, max_length=200)),
                ('age', models.CharField(default=None, max_length=10)),
                ('complaint', models.CharField(default=None, max_length=300)),
                ('Phone_number', models.CharField(default=None, max_length=15)),
                ('currentdate', models.DateField()),
                ('callormsg', models.CharField(default=None, max_length=200)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('branch', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('predpaidby', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('sourrcdts', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.sourcedetails')),
            ],
        ),
        migrations.CreateModel(
            name='followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followupdate', models.DateField()),
                ('remainderdate', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(default=None, max_length=300)),
                ('enqid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.enquiry')),
                ('followedby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
