# Generated by Django 5.1.1 on 2024-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0005_sourcedetails_enquiry_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='language',
            field=models.CharField(default='English', max_length=800),
        ),
    ]
