# Generated by Django 5.1.1 on 2024-11-12 06:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0007_delete_nexdoctorprescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexDoctorPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=datetime.date.today)),
                ('complaint', models.CharField(max_length=700)),
                ('diet', models.CharField(max_length=700)),
                ('note', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_stock_medicinename', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.PositiveIntegerField()),
                ('dosage', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, max_length=700)),
                ('medicinename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.medicinemaster')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='ayurvedaapp.nexdoctorprescription')),
            ],
        ),
    ]
