# Generated by Django 5.1.1 on 2024-11-12 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0008_nexdoctorprescription_medicationentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='casehistoryErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('related_mrno', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
