# Generated by Django 5.1.1 on 2024-11-22 12:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0014_staffdetails_deleted_staffdetails_deleted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalfollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(default=datetime.date.today)),
                ('nextfollowupdate', models.DateField(default=datetime.date.today)),
                ('progressnote', models.TextField(blank=True, null=True)),
                ('currentsymptioms', models.TextField(blank=True, null=True)),
                ('Mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('followupstaffno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
