# Generated by Django 5.1.1 on 2024-12-02 05:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0016_remove_nexdoctorprescription_diet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clairvedaCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Consultation', 'Consultation'), ('Followup', 'Follow Up')], max_length=20)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('drug_history', models.TextField(blank=True)),
                ('present_complaint', models.TextField()),
                ('final_diagnosis', models.CharField(max_length=255)),
                ('test_needed', models.CharField(blank=True, max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.diet')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_histories', to='ayurvedaapp.patient_details')),
            ],
        ),
        migrations.CreateModel(
            name='clairvedaFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='ayurvedaapp.clairvedacasehistory')),
                ('handledbystaff', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='clairvedaFollowUpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='followup_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ayurvedaapp.clairvedafollowup')),
            ],
        ),
        migrations.CreateModel(
            name='clairvedaPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptiondate', models.DateField(default=datetime.date.today)),
                ('medicine_name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('dosage', models.CharField(choices=[('OD', 'Once a Day'), ('BD', 'Twice a Day'), ('TD', 'Three times a Day'), ('Other', 'Other')], max_length=50)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ayurvedaapp.clairvedacasehistory')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ayurvedaapp.clairvedafollowup')),
                ('prescribeddoctor', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='clairvedcasehistrypersonalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('height', models.FloatField(blank=True, default=0.0)),
                ('clrcasehistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.clairvedacasehistory')),
                ('mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
            ],
        ),
    ]
