# Generated by Django 5.1.1 on 2024-12-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0023_alter_followup_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='contactno',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
