# Generated by Django 5.1.1 on 2025-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0024_appointments_contactno_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstockdetails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalstockdetails',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedetails',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcedetails',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
