# Generated by Django 5.1.5 on 2025-02-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0026_followupcalldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='uniqueid',
        ),
    ]
