# Generated by Django 5.1.5 on 2025-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0027_remove_enquiry_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldetails',
            name='Email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medicinemaster',
            name='racknumber',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='Email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Email',
            field=models.EmailField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Staff_firstname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Staff_lastname',
            field=models.CharField(max_length=300),
        ),
    ]
