# Generated by Django 5.1.5 on 2025-03-17 04:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0031_nextreatmentdetailschild_deletedstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ippatientadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.TextField(blank=True, default=None, null=True)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('age', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reasonforadmission', models.TextField(blank=True, default=None, null=True)),
                ('MR_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
            ],
        ),
        migrations.CreateModel(
            name='Room_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floorno', models.CharField(max_length=50)),
                ('Blockno', models.CharField(max_length=50)),
                ('Roomno', models.CharField(max_length=50)),
                ('Room_type', models.CharField(max_length=300)),
                ('is_available', models.BooleanField(default=True)),
                ('bed_type', models.CharField(default=None, max_length=300)),
                ('rate', models.CharField(default=None, max_length=10)),
                ('branchidrm', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='br_id', to='ayurvedaapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ippatientroombooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Date', models.DateField(default=datetime.date.today)),
                ('admissiontime', models.CharField(max_length=100)),
                ('emergencycontact', models.CharField(max_length=100)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('MR_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('admitteddepartmnt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.department')),
                ('admitteddoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
                ('branchdt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('roomdt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.room_details')),
            ],
        ),
    ]
