# Generated by Django 5.1.5 on 2025-03-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0036_ippatientroombooking_ipno_ipdailymedicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptreatmentdetails',
            name='treatmentcount',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
