# Generated by Django 5.1.5 on 2025-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0042_clairvedaprescription_physicalstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clairvedacasehistory',
            name='deletestatus',
            field=models.BooleanField(default=False),
        ),
    ]
