# Generated by Django 5.1.5 on 2025-05-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0051_patientdischarge_accomadationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='bystander_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='need_bystander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='need_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.packagemaster'),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='total_package_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='totalpaidamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
