# Generated by Django 5.2.1 on 2025-05-14 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0053_ippackagepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientroombooking',
            name='admissionenddate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
