# Generated by Django 5.2.1 on 2025-06-12 08:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0057_ippatientadmission_advancedue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRoom_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floorno', models.CharField(max_length=50)),
                ('Roomno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='oppatienttreamentroombooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('bookingdate', models.DateField(default=datetime.date.today)),
                ('bookingstarttime', models.TimeField()),
                ('bookingendtime', models.TimeField()),
                ('bookingstatus', models.BooleanField(default=True)),
                ('branchdt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('handledystaff', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
                ('patientid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('preparedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('treatmntroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.treatmentroom_details')),
            ],
        ),
    ]
