# Generated by Django 5.2 on 2025-06-18 10:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0059_oppatienttreamentroombooking_bookingenddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='proceduredt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedurename', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='oppatienttimeslotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=30)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('bookingdate', models.DateField(default=datetime.date.today)),
                ('bookingstarttime', models.TimeField()),
                ('bookingendtime', models.TimeField()),
                ('bookingstatus', models.BooleanField(default=True)),
                ('bookingenddate', models.DateField(default=datetime.date.today)),
                ('branchdt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('handledystaff', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
                ('patientid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('preparedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('proceduretaken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.proceduredt')),
            ],
        ),
    ]
