# Generated by Django 5.2.4 on 2025-08-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0068_prescriptionnew_qtyprescriped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='Fee',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='appointmentinvoicemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentInvoicenumber', models.CharField(default=None, max_length=400)),
                ('currentdate', models.DateField()),
                ('subtotal', models.FloatField()),
                ('tax', models.FloatField()),
                ('shipping', models.FloatField()),
                ('total', models.FloatField()),
                ('patientname', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('patientphno', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('discount', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('consultationfee', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('consultationfeecumregfee', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cancelstatus', models.BooleanField(default=False)),
                ('Mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('hospitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.hospitaldetails')),
                ('preparedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
            ],
        ),
    ]
