# Generated by Django 5.2.4 on 2025-08-31 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0069_ratemaster_appointments_fee_appointmentinvoicemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistorytreatmentplan',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratfollowp', to='ayurvedaapp.clairvedafollowup'),
        ),
    ]
