# Generated by Django 5.2.4 on 2025-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0072_appointmentinvoicemaster_payementmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechild',
            name='cgst',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='sgst',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
