# Generated by Django 5.2.4 on 2025-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0076_branch_hosporclinic_alter_branch_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='compositiontax',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Branch_Address',
            field=models.CharField(max_length=300),
        ),
    ]
