# Generated by Django 5.1.3 on 2025-10-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0083_alter_prescriptionnew_case_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistorydietplan',
            name='case_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casehistdietplan', to='ayurvedaapp.clairvedacasehistory'),
        ),
        migrations.AlterField(
            model_name='casehistorydoctorsnote',
            name='case_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorsnote', to='ayurvedaapp.clairvedacasehistory'),
        ),
        migrations.AlterField(
            model_name='casehistorymedicalandsurgicalhistory',
            name='case_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casehistory', to='ayurvedaapp.clairvedacasehistory'),
        ),
        migrations.AlterField(
            model_name='casehistorytreatmentplan',
            name='case_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casetreatmntplan', to='ayurvedaapp.clairvedacasehistory'),
        ),
    ]
