# Generated by Django 5.1.3 on 2025-10-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0084_alter_casehistorydietplan_case_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistorylabtestrequisition',
            name='case_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casehistlabtest', to='ayurvedaapp.clairvedacasehistory'),
        ),
    ]
