# Generated by Django 5.1.3 on 2025-11-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0088_branch_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoicechild',
            name='returned_qty',
            field=models.IntegerField(default=0),
        ),
    ]
