# Generated by Django 5.2.4 on 2025-12-10 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0089_newinvoicechild_returned_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistorylabresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
