# Generated by Django 5.2.4 on 2025-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0090_alter_casehistorylabresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoicechild',
            name='manufacturedate',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
