# Generated by Django 5.2.4 on 2025-12-18 18:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0092_paymentupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('FIRST_VISIT', 'First Visit Registration Fee'), ('FOLLOW_UP', 'Follow-up Visit Fee'), ('PACKAGE', 'Package Visit Fee')], max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('visit_count_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('time_period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisitTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fee_type', models.CharField(default='REGULAR', max_length=50)),
                ('is_first_visit_in_period', models.BooleanField(default=False)),
                ('period_start_date', models.DateField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_tracking', to='ayurvedaapp.appointments')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_tracking', to='ayurvedaapp.patient_details')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
