# Generated by Django 5.2.4 on 2025-12-23 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0093_appointmentfeerule_patientvisittracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore')], max_length=10)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('action_time', models.TimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.medicinemaster')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.physicalstockdetails')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.storedetails')),
            ],
        ),
    ]
