# Generated by Django 5.2.4 on 2026-01-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0095_paymentupdatelog_previous_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpdateLognew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_payment_mode', models.CharField(max_length=300)),
                ('updated_payment_mode', models.CharField(max_length=300)),
                ('previous_cash_amount', models.CharField(default='0', max_length=400)),
                ('previous_gpay_amount', models.CharField(default='0', max_length=400)),
                ('previous_card_amount', models.CharField(default='0', max_length=400)),
                ('updated_cash_amount', models.CharField(default='0', max_length=400)),
                ('updated_gpay_amount', models.CharField(default='0', max_length=400)),
                ('updated_card_amount', models.CharField(default='0', max_length=400)),
                ('previous_total', models.FloatField(default=0)),
                ('updated_total', models.FloatField(default=0)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_update_logs', to='ayurvedaapp.newinvoicemaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_updates_made', to='ayurvedaapp.staffallocation')),
            ],
            options={
                'verbose_name': 'Pharmacy Invoice Payment Update Log',
                'verbose_name_plural': 'Pharmacy Invoice Payment Update Logs',
                'ordering': ['-updated_date'],
            },
        ),
    ]
