# Generated by Django 6.0 on 2026-02-13 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0101_assignedappointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('original_medicine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_noofdays', models.CharField(blank=True, max_length=400, null=True)),
                ('original_moringtime', models.CharField(blank=True, max_length=100, null=True)),
                ('original_noontime', models.CharField(blank=True, max_length=100, null=True)),
                ('original_nighttime', models.CharField(blank=True, max_length=100, null=True)),
                ('original_beforeorafterdiet', models.CharField(blank=True, max_length=100, null=True)),
                ('original_medicineguideline', models.CharField(blank=True, max_length=400, null=True)),
                ('original_qtyprescriped', models.IntegerField(blank=True, null=True)),
                ('original_medicine_id', models.IntegerField(blank=True, null=True)),
                ('original_physicalstock_id', models.IntegerField(blank=True, null=True)),
                ('original_prescription_date', models.DateField(blank=True, null=True)),
                ('original_patient_id', models.IntegerField(blank=True, null=True)),
                ('original_doctor_id', models.IntegerField(blank=True, null=True)),
                ('new_medicine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_noofdays', models.CharField(blank=True, max_length=400, null=True)),
                ('new_moringtime', models.CharField(blank=True, max_length=100, null=True)),
                ('new_noontime', models.CharField(blank=True, max_length=100, null=True)),
                ('new_nighttime', models.CharField(blank=True, max_length=100, null=True)),
                ('new_beforeorafterdiet', models.CharField(blank=True, max_length=100, null=True)),
                ('new_medicineguideline', models.CharField(blank=True, max_length=400, null=True)),
                ('new_qtyprescriped', models.IntegerField(blank=True, null=True)),
                ('new_medicine_id', models.IntegerField(blank=True, null=True)),
                ('new_physicalstock_id', models.IntegerField(blank=True, null=True)),
                ('new_prescription_date', models.DateField(blank=True, null=True)),
                ('new_doctor_id', models.IntegerField(blank=True, null=True)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('action_time', models.TimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.patient_details')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.prescriptionnew')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
