# Generated by Django 5.2.5 on 2026-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0107_proformainvoice_purchaseorder_proformaitem_poitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
