# Generated by Django 5.2.5 on 2026-03-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0113_b2binvoice_b2binvoiceitem_b2cinvoice_b2cinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2binvoice',
            name='buyer_state',
            field=models.CharField(blank=True, default='Kerala', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='buyer_state_code',
            field=models.CharField(blank=True, default='32', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='buyers_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='buyers_order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='consignee_state',
            field=models.CharField(blank=True, default='Kerala', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='consignee_state_code',
            field=models.CharField(blank=True, default='32', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='delivery_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='dispatch_doc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='dispatched_through',
            field=models.CharField(blank=True, default='By Road', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='payment_mode',
            field=models.CharField(blank=True, default='Cash', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoice',
            name='terms_of_delivery',
            field=models.CharField(blank=True, default='F.O.R. Destination', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2cinvoice',
            name='bill_to_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2cinvoice',
            name='bill_to_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='b2cinvoice',
            name='customer_state_code',
            field=models.CharField(blank=True, default='32', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='b2cinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2cinvoice',
            name='transport_mode',
            field=models.CharField(blank=True, default='By Road', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='b2cinvoice',
            name='customer_state',
            field=models.CharField(blank=True, default='Kerala', max_length=100, null=True),
        ),
    ]
