# Generated by Django 5.2.5 on 2026-03-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0115_alter_proformainvoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='manufacturer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='medicine_master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='physical_stock_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2binvoiceitem',
            name='unit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
