# Generated by Django 5.2.8 on 2026-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0127_headerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvoicemaster',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='gpay_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='payment_status',
            field=models.CharField(default='Paid', max_length=20),
        ),
    ]
