# Generated by Django 5.1.4 on 2026-06-16 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0142_debitnote_debitnoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstockdetails',
            name='wholesale_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('supplier_bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_bill_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(default='Net 30', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stock_updated', models.BooleanField(default=False, help_text='Whether stock was updated when invoice was created')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.comapany')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.storedetails')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.supplier')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=500)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.IntegerField()),
                ('free_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wholesalerate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retalrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ayurvedaapp.purchaseinvoice')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.medicinemaster')),
            ],
        ),
    ]
