# Generated by Django 5.2.11 on 2026-06-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0144_debitnoteitem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistryvitals',
            name='pr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='casehistryvitals',
            name='spo2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='casehistryvitals',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
