# Generated by Django 5.2.11 on 2026-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0146_purchaseinvoiceitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoicemaster',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
