# Generated by Django 5.2.11 on 2026-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0151_remove_ippackagepayment_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='ipnumber',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
