# Generated by Django 5.2.11 on 2026-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0158_birthregister_deathregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthregister',
            name='child_op',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
