# Generated by Django 5.2.11 on 2026-07-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0160_alter_birthregister_child_op_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistorylabtestrequisition',
            name='labtestgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labtestmaster'),
        ),
    ]
