# Generated by Django 5.2.11 on 2026-07-09 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0164_casehistorylabresult_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('asset_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('asset_added_date', models.DateField(auto_now_add=True)),
                ('manufacturer', models.CharField(blank=True, max_length=300, null=True)),
                ('supplier', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('physical_location', models.CharField(blank=True, max_length=200, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='ayurvedaapp.branch')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffallocation')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action: create / update / transfer / maintenance / dispose / restore', max_length=20)),
                ('old_value', models.JSONField(blank=True, default=dict, null=True)),
                ('new_value', models.JSONField(blank=True, default=dict, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('action_time', models.TimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ayurvedaapp.asset')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffallocation')),
            ],
            options={
                'verbose_name': 'Asset Audit Log',
                'verbose_name_plural': 'Asset Audit Logs',
                'ordering': ['-action_date', '-action_time'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(editable=False, help_text='Transfer Number (Auto)', max_length=50, unique=True)),
                ('received_by', models.CharField(blank=True, help_text='Received By', max_length=300, null=True)),
                ('transfer_date', models.DateField(help_text='Transfer Date (No Future Date)')),
                ('remarks', models.TextField(blank=True, help_text='Remarks (Optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_editable', models.BooleanField(default=True, help_text='Admin can edit if required')),
                ('asset', models.ForeignKey(help_text='Asset', on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='ayurvedaapp.asset')),
                ('department', models.ForeignKey(blank=True, help_text='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers', to='ayurvedaapp.department')),
                ('from_branch', models.ForeignKey(help_text='From Branch', on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_from', to='ayurvedaapp.branch')),
                ('to_branch', models.ForeignKey(help_text='To Branch', on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_to', to='ayurvedaapp.branch')),
                ('transferred_by', models.ForeignKey(help_text='Transferred By (Login Staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred', to='ayurvedaapp.staffallocation')),
            ],
            options={
                'verbose_name': 'Asset Transfer',
                'verbose_name_plural': 'Asset Transfers',
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['transfer_number'], name='ayurvedaapp_transfe_4e0603_idx'), models.Index(fields=['asset', 'transfer_date'], name='ayurvedaapp_asset_i_0b1b4e_idx'), models.Index(fields=['from_branch', 'to_branch'], name='ayurvedaapp_from_br_c60472_idx')],
            },
        ),
    ]
