# Generated by Django 5.2.11 on 2026-07-09 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0167_assettransfer_branch_assettransfer_from_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gin_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('gin_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gin_branch', to='ayurvedaapp.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gin_created', to='ayurvedaapp.staffallocation')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gin_departments', to='ayurvedaapp.department')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gin_staff', to='ayurvedaapp.staffdetails')),
            ],
            options={
                'verbose_name': 'Goods Issue Note',
                'verbose_name_plural': 'Goods Issue Notes',
                'ordering': ['-gin_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('manufacturer_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ayurvedaapp.inventorycompany')),
                ('gin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ayurvedaapp.goodsissuenote')),
                ('inventory_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ayurvedaapp.inventorystockdetails')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ayurvedaapp.inventorymaster')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ayurvedaapp.supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ayurvedaapp.unitdt')),
            ],
        ),
    ]
