# Generated by Django 5.2.11 on 2026-07-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0169_appointmentstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentstatus',
            table=None,
        ),
    ]
