# Generated by Django 5.2.11 on 2026-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0170_alter_appointmentstatus_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfee',
            name='visit_type',
            field=models.CharField(max_length=50),
        ),
    ]
