# Generated by Django 5.2.11 on 2026-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0171_alter_appointmentfee_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfee',
            name='visit_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Followup', 'Followup'), ('Revisit', 'Revisit'), ('Whatsapp', 'Whatsapp'), ('Camp', 'Camp'), ('Treatment', 'Treatment'), ('Treatment Revisit', 'Treatment Revisit'), ('zoho online consultation', 'Zoho Online Consultation'), ('zoho online revisit', 'Zoho Online Revisit'), ('whatsapp', 'WhatsApp'), ('whatsapp revisit', 'WhatsApp Revisit')], max_length=50),
        ),
    ]
