# Generated by Django 5.2.11 on 2026-07-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0172_alter_appointmentfee_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='status_name',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Followup', 'Followup'), ('Revisit', 'Revisit'), ('Whatsapp', 'Whatsapp'), ('Camp', 'Camp'), ('Treatment', 'Treatment'), ('Treatment Revisit', 'Treatment Revisit'), ('zoho online consultation', 'Zoho Online Consultation'), ('zoho online revisit', 'Zoho Online Revisit'), ('whatsapp', 'WhatsApp'), ('whatsapp revisit', 'WhatsApp Revisit')], max_length=200, unique=True),
        ),
    ]
