# Generated by Django 5.2.11 on 2026-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0173_alter_appointmentstatus_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='status_name',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Followup', 'Followup'), ('Revisit', 'Revisit'), ('Whatsapp', 'Whatsapp'), ('Camp', 'Camp')], max_length=200, unique=True),
        ),
    ]
