# Generated by Django 5.2.11 on 2026-07-13 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0175_alter_appointmentfee_visit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRevisitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisit_days_range', models.IntegerField(default=20, help_text='Number of days within which a patient is considered a revisit')),
                ('max_revisit_count', models.IntegerField(default=3, help_text='Maximum number of revisits allowed for a patient')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_detect_revisit', models.BooleanField(default=True, help_text='Automatically detect and mark appointment as revisit')),
                ('revisit_fee_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override fee for revisit appointments (leave blank to use standard fee)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisit_settings', to='ayurvedaapp.staffdetails')),
            ],
            options={
                'verbose_name_plural': 'Doctor Revisit Settings',
                'ordering': ['branch', 'doctor'],
                'unique_together': {('branch', 'doctor')},
            },
        ),
    ]
