# Generated by Django 5.2.11 on 2026-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0176_doctorrevisitsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfee',
            name='max_visit_count',
            field=models.IntegerField(default=3, help_text='Maximum number of revisits allowed for a patient'),
        ),
        migrations.AddField(
            model_name='appointmentfee',
            name='no_of_days',
            field=models.IntegerField(default=20, help_text='Number of days within which a patient is considered a revisit'),
        ),
        migrations.DeleteModel(
            name='DoctorRevisitSettings',
        ),
    ]
