# Generated by Django 5.2.11 on 2026-07-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0177_appointmentfee_max_visit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfee',
            name='max_visit_count',
            field=models.IntegerField(default=3, help_text='Maximum number of visits allowed for a patient'),
        ),
        migrations.AlterField(
            model_name='appointmentfee',
            name='no_of_days',
            field=models.IntegerField(default=20, help_text='Number of days within which a patient is considered a visit'),
        ),
        migrations.CreateModel(
            name='PatientVisitCycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consultation_count', models.IntegerField(default=1)),
                ('revisit_count', models.IntegerField(default=0)),
                ('followup_count', models.IntegerField(default=0)),
                ('total_visits_in_cycle', models.IntegerField(default=1)),
                ('total_fee_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_revisit_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_followup_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('consultation_days', models.IntegerField(default=0)),
                ('revisit_days', models.IntegerField(default=0)),
                ('max_revisit_count', models.IntegerField(default=0)),
                ('followup_days', models.IntegerField(default=0)),
                ('max_followup_count', models.IntegerField(default=0)),
                ('consultation_fee_setting', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revisit_fee_setting', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('followup_fee_setting', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_status', models.CharField(choices=[('Consultation', 'Consultation'), ('Revisit', 'Revisit'), ('Followup', 'Followup')], max_length=50)),
                ('days_from_consultation', models.IntegerField(default=0)),
                ('is_cycle_active', models.BooleanField(default=True)),
                ('is_cycle_closed', models.BooleanField(default=False)),
                ('cycle_end_date', models.DateField(blank=True, null=True)),
                ('cycle_closed_reason', models.CharField(blank=True, choices=[('max_revisit_reached', 'Max Revisit Count Reached'), ('max_followup_reached', 'Max Followup Count Reached'), ('consultation_days_expired', 'Consultation Days Expired'), ('manual_close', 'Manually Closed')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch')),
                ('consultation_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cycle', to='ayurvedaapp.appointments')),
                ('current_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cycle', to='ayurvedaapp.appointments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_cycles', to='ayurvedaapp.staffdetails')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_cycles', to='ayurvedaapp.patient_details')),
            ],
            options={
                'verbose_name_plural': 'Patient Visit Cycle Logs',
                'ordering': ['-consultation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisitCycleAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Consultation', 'Consultation'), ('Revisit', 'Revisit'), ('Followup', 'Followup')], max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_in_cycle', models.IntegerField(default=0)),
                ('days_from_consultation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_appointments', to='ayurvedaapp.appointments')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ayurvedaapp.patientvisitcyclelog')),
            ],
            options={
                'verbose_name_plural': 'Cycle Appointments',
                'ordering': ['order_in_cycle', 'appointment__Appointment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='patientvisitcyclelog',
            index=models.Index(fields=['patient', 'doctor'], name='ayurvedaapp_patient_aa110d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisitcyclelog',
            index=models.Index(fields=['consultation_date'], name='ayurvedaapp_consult_7f1764_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisitcyclelog',
            index=models.Index(fields=['is_cycle_active'], name='ayurvedaapp_is_cycl_fed4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisitcyclelog',
            index=models.Index(fields=['current_status'], name='ayurvedaapp_current_87faab_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisitcycleappointment',
            index=models.Index(fields=['cycle', 'status'], name='ayurvedaapp_cycle_i_9e336c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisitcycleappointment',
            index=models.Index(fields=['appointment'], name='ayurvedaapp_appoint_b56929_idx'),
        ),
    ]
