# Generated by Django 5.2.11 on 2026-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0178_alter_appointmentfee_max_visit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentfee',
            name='max_visit_count',
            field=models.IntegerField(default=1, help_text='Maximum number of visits allowed for a patient'),
        ),
        migrations.AlterField(
            model_name='appointmentfee',
            name='no_of_days',
            field=models.IntegerField(default=1, help_text='Number of days within which a patient is considered a visit'),
        ),
    ]
