# Generated by Django 5.2.11 on 2026-07-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0179_alter_appointmentfee_max_visit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfee',
            name='visit_order_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
