# Generated by Django 5.2.11 on 2026-07-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0180_appointmentfee_visit_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentfee',
            name='visit_order_no',
        ),
    ]
