# Generated by Django 5.2.11 on 2026-07-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0181_remove_appointmentfee_visit_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentfee',
            name='max_visit_count',
        ),
        migrations.RemoveField(
            model_name='appointmentfee',
            name='no_of_days',
        ),
    ]
