# Generated by Django 5.2.11 on 2026-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0182_remove_appointmentfee_max_visit_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitcycleappointment',
            name='status',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Followup', 'Followup'), ('Revisit', 'Revisit'), ('Whatsapp', 'Whatsapp'), ('Camp', 'Camp')], max_length=50),
        ),
    ]
