# Generated by Django 5.2.11 on 2026-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0183_alter_patientvisitcycleappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitcycleappointment',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
