# Generated by Django 5.2.11 on 2026-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0184_alter_patientvisitcycleappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
