# Generated by Django 5.1.4 on 2026-07-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0185_ippatientadmission_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='admitted_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_admissions', to='ayurvedaapp.staffallocation'),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_admissions', to='ayurvedaapp.department'),
        ),
    ]
