# Generated by Django 5.2.11 on 2026-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0185_ippatientadmission_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='reg_Fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
