# Generated by Django 5.1.4 on 2026-07-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0186_ippatientadmission_admitted_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('ip_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='ayurvedaapp.ippatientadmission')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
            ],
            options={
                'verbose_name': 'IP Advance Payment',
                'verbose_name_plural': 'IP Advance Payments',
                'db_table': 'ip_advance_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPAdvancePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('advance', 'Advance Payment'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='ayurvedaapp.ippatientadmission')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ipadvancepayment')),
            ],
            options={
                'db_table': 'ip_advance_payment_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
