# Generated by Django 5.1.4 on 2026-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0187_ipadvancepayment_ipadvancepaymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipadvancepayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ipadvancepaymenthistory',
            options={},
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='total_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='ipadvancepayment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ipadvancepaymenthistory',
            table=None,
        ),
    ]
