# Generated by Django 5.1.4 on 2026-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0188_alter_ipadvancepayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
