# Generated by Django 5.1.4 on 2026-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0189_ipbill_advance_paid_ipbill_balance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='bank_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='refundamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='upi_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
