# Generated by Django 5.1.4 on 2026-07-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0190_ipbill_bank_amount_ipbill_card_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischarge',
            old_name='sfirst_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patient_details',
            name='reg_Fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='discharge_summary_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='physical_examinations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PreAppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('contactno', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.designation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
            ],
        ),
    ]
