# Generated by Django 5.1.4 on 2026-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0191_rename_sfirst_name_patientdischarge_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischarge',
            name='first_name',
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='sfirst_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
