# Generated by Django 5.2.11 on 2026-07-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0192_remove_patientdischarge_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='procedure_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
# Generated by Django 5.2.11 on 2026-07-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0192_remove_patientdischarge_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='procedure_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
# Generated by Django 5.2.11 on 2026-07-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0192_remove_patientdischarge_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='procedure_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
