# Generated by Django 5.2.11 on 2026-07-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0193_ipbill_procedure_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisitcyclelog',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='patientvisitcyclelog',
            name='consultation_appointment',
        ),
        migrations.RemoveField(
            model_name='patientvisitcyclelog',
            name='current_appointment',
        ),
        migrations.RemoveField(
            model_name='patientvisitcyclelog',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientvisitcyclelog',
            name='patient',
        ),
        migrations.DeleteModel(
            name='PatientVisitCycleAppointment',
        ),
        migrations.DeleteModel(
            name='PatientVisitCycleLog',
        ),
    ]
