# Generated by Django 5.2.11 on 2026-07-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0194_remove_patientvisitcyclelog_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_mr_no', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('patient_age', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(default='Cash', max_length=20)),
                ('payment_status', models.CharField(default='Paid', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_invoices', to='ayurvedaapp.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_registration_invoices', to='ayurvedaapp.staffallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_invoices', to='ayurvedaapp.staffdetails')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.hospitaldetails')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_invoices', to='ayurvedaapp.patient_details')),
            ],
        ),
    ]
