# Generated by Django 5.2.11 on 2026-07-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0195_registrationfeeinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationfeeinvoice',
            old_name='total',
            new_name='registration_fee',
        ),
    ]
