# Generated by Django 5.2.11 on 2026-07-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0196_rename_total_registrationfeeinvoice_registration_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Complaint Name')),
                ('status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_complaints', to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
