# Generated by Django 5.2.11 on 2026-07-30 06:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0197_complaintsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvoicemaster',
            name='ip_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newinvoicemaster',
            name='ip_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ipexpandedbillproceduredetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.TextField()),
                ('count', models.TextField(blank=True, default='1', null=True)),
                ('rate_per_procedure', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_procedure', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('ipbilldt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ipbill')),
                ('ipno', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.proceduremaster')),
            ],
        ),
    ]
