# Generated by Django 5.2.11 on 2026-07-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0198_labinvoicemaster_ip_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='labipcredit',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='pharmacyipcredit',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
