# Generated by Django 5.2.11 on 2026-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0199_ipbill_labipcredit_ipbill_pharmacyipcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='admission_category',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Elective', 'Elective'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='admission_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='booking_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='consultant_incharge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='estimated_stay_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='procedures_planned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='referral_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='surgical_procedure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
