# Generated by Django 5.2.11 on 2026-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0200_ippatientadmission_admission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsmaster',
            name='name',
            field=models.TextField(),
        ),
    ]
