# Generated by Django 5.2.11 on 2026-07-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0201_alter_complaintsmaster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='casehistoryprocedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deletedstatus', models.BooleanField(default=False)),
                ('case_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.clairvedacasehistory')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.clairvedafollowup')),
                ('patient', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('prepairedby', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.proceduremaster')),
            ],
        ),
    ]
