# Generated by Django 5.1.1 on 2024-11-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0002_alter_casehistrypersonalinfo_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemaster',
            name='currentdate',
            field=models.DateField(),
        ),
    ]
