# Generated by Django 5.1.1 on 2024-11-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0003_alter_invoicemaster_currentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='enqid',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='followedby',
        ),
        migrations.DeleteModel(
            name='enquiry',
        ),
        migrations.DeleteModel(
            name='followup',
        ),
    ]
