# Generated by Django 5.1.1 on 2024-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0009_casehistoryerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
