# Generated by Django 5.1.1 on 2024-11-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0010_enquiry_deleted_enquiry_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechild',
            name='baseqty',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='tax',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='taxamount',
            field=models.FloatField(default=None),
        ),
    ]
