# Generated by Django 5.1.1 on 2024-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0011_invoicechild_baseqty_invoicechild_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='district',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
