# Generated by Django 5.1.1 on 2024-11-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0015_medicalfollowup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nexdoctorprescription',
            name='diet',
        ),
        migrations.AddField(
            model_name='nexdoctorprescription',
            name='dietid',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.diet'),
        ),
    ]
