# Generated by Django 5.1.1 on 2024-12-05 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0017_clairvedacasehistory_clairvedafollowup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clairvedacasehistory',
            name='prepairedby',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepaidstaff', to='ayurvedaapp.staffdetails'),
        ),
    ]
