# Generated by Django 5.1.1 on 2024-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0018_clairvedacasehistory_prepairedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clairvedcasehistrypersonalinfo',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clairvedcasehistrypersonalinfo',
            name='height',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='clairvedcasehistrypersonalinfo',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
