# Generated by Django 5.1.1 on 2024-12-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0019_alter_clairvedcasehistrypersonalinfo_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='casehistoryresultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='casehistory_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('casehistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseresultreports', to='ayurvedaapp.clairvedacasehistory')),
            ],
        ),
    ]
