# Generated by Django 5.1.1 on 2024-12-07 07:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0020_casehistoryresultreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextreatmentdetailschild',
            name='treatment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nextreatmentdetailsmaster',
            name='branchstff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch'),
        ),
        migrations.AddField(
            model_name='nextreatmentdetailsmaster',
            name='prepairedstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails'),
        ),
    ]
