# Generated by Django 5.1.1 on 2024-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0021_nextreatmentdetailschild_treatment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
