# Generated by Django 5.1.1 on 2024-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0022_patient_details_deleted_patient_details_deleted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='remarks',
            field=models.TextField(default=None),
        ),
    ]
