# Generated by Django 5.1.1 on 2025-01-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0025_physicalstockdetails_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='followupcalldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField()),
                ('callorstatus', models.TextField(default=None)),
                ('status', models.TextField(default=None)),
                ('enqid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.enquiry')),
                ('followedby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
