# Generated by Django 5.1.5 on 2025-02-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0028_alter_hospitaldetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='address',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
