# Generated by Django 5.1.5 on 2025-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0029_patient_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextreatmentdetailschild',
            name='treatmenttime',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
