# Generated by Django 5.1.5 on 2025-03-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0030_nextreatmentdetailschild_treatmenttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextreatmentdetailschild',
            name='deletedstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nextreatmentdetailsmaster',
            name='casehistoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.clairvedacasehistory'),
        ),
    ]
