# Generated by Django 5.1.5 on 2025-03-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0032_ippatientadmission_room_details_ippatientroombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='wardbedno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room_details',
            name='wardorroom',
            field=models.CharField(default='room', max_length=300),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='Room_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='room_details',
            name='Roomno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
