# Generated by Django 5.1.5 on 2025-03-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0033_room_details_wardbedno_room_details_wardorroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientroombooking',
            name='accommodation_type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ippatientroombooking',
            name='bed_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_number', to='ayurvedaapp.room_details'),
        ),
        migrations.AddField(
            model_name='ippatientroombooking',
            name='floor_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ippatientroombooking',
            name='room_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_number', to='ayurvedaapp.room_details'),
        ),
        migrations.AddField(
            model_name='ippatientroombooking',
            name='room_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ippatientroombooking',
            name='admissiontime',
            field=models.TimeField(),
        ),
    ]
