# Generated by Django 5.1.5 on 2025-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0034_ippatientroombooking_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='Admittedstatus',
            field=models.BooleanField(default=True),
        ),
    ]
