# Generated by Django 5.1.5 on 2025-03-26 05:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0035_ippatientadmission_admittedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientroombooking',
            name='ipno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission'),
        ),
        migrations.CreateModel(
            name='ipdailymedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('medicinegiventime', models.TextField(blank=True, default=None, null=True)),
                ('count', models.TextField(blank=True, default=None, null=True)),
                ('dosage', models.TextField(blank=True, default=None, null=True)),
                ('MR_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('ipno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('medicinename', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.medicinemaster')),
            ],
        ),
        migrations.CreateModel(
            name='iptreatmentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmenttime', models.TextField(blank=True, default=None, null=True)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('treatment_date', models.DateField(default=datetime.date.today)),
                ('handled_by', models.TextField(default=None)),
                ('given_by', models.TextField(default=None)),
                ('deletedstatus', models.BooleanField(default=False)),
                ('MR_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('ipno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('tratmntid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.treatment_master')),
            ],
        ),
    ]
