# Generated by Django 5.1.5 on 2025-03-31 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0037_iptreatmentdetails_treatmentcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_summary', models.TextField()),
                ('discharged_date', models.DateField()),
                ('next_checkup_date', models.DateField()),
                ('additional_notes', models.TextField()),
                ('sfirst_name', models.CharField(default=None, max_length=100)),
                ('dischargedstaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
                ('ipptno', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
            ],
        ),
    ]
