# Generated by Django 5.1.5 on 2025-03-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0038_patientdischarge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdailymedicine',
            name='physicalstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.physicalstockdetails'),
        ),
    ]
