# Generated by Django 5.1.5 on 2025-03-31 06:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0039_ipdailymedicine_physicalstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medicine_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('treatment_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_date', models.DateField(default=datetime.date.today)),
                ('food_expenses', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('discharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='ayurvedaapp.patientdischarge')),
                ('ip_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='ayurvedaapp.ippatientadmission')),
            ],
        ),
    ]
