# Generated by Django 5.1.5 on 2025-04-01 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0040_ipbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrno', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('action', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore')], max_length=10)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('action_time', models.TimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
