# Generated by Django 5.1.5 on 2025-04-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0041_patientauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clairvedaprescription',
            name='physicalstock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.physicalstockdetails'),
        ),
    ]
