# Generated by Django 5.1.5 on 2025-04-08 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0043_clairvedacasehistory_deletestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(default=django.utils.timezone.now)),
                ('change_time', models.TimeField(default=django.utils.timezone.now)),
                ('no_of_days_stayed', models.PositiveIntegerField(default=1)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
                ('from_room_or_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_changes_from', to='ayurvedaapp.room_details')),
                ('ipno', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('to_room_or_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_changes_to', to='ayurvedaapp.room_details')),
            ],
        ),
    ]
