# Generated by Django 5.1.5 on 2025-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0044_roomchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='ipinvoicenumber',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='ipbill',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
