# Generated by Django 5.1.5 on 2025-04-10 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0045_ipbill_ipinvoicenumber_ipbill_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipbill',
            name='billingstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation'),
        ),
    ]
