# Generated by Django 5.1.5 on 2025-04-11 11:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0046_ipbill_billingstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipexpandedbillmedicinedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.TextField()),
                ('count', models.TextField(blank=True, default=None, null=True)),
                ('dosage', models.TextField(blank=True, default=None, null=True)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('rate_per_medicine', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalmedicine', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ipbilldt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ipbill')),
                ('ipno', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('physicalstock', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.physicalstockdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ipexpandedbillotherexpensesdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('ipbilldt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ipbill')),
                ('ipno', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
            ],
        ),
        migrations.CreateModel(
            name='IPExpandedBillRoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.PositiveIntegerField(default=1)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanded_room_details', to='ayurvedaapp.ipbill')),
                ('ipno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='ayurvedaapp.ippatientadmission')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.room_details')),
            ],
        ),
        migrations.CreateModel(
            name='ipexpandedbilltreatmentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentcount', models.TextField(blank=True, default=None, null=True)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('rate_per_treatment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_treatmentrate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ipbilldt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ipbill')),
                ('ipno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('tratmntid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.treatment_master')),
            ],
        ),
    ]
