# Generated by Django 5.1.5 on 2025-04-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0047_ipexpandedbillmedicinedetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='packagemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.TextField(blank=True, null=True)),
                ('packagedetails', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('branchdt', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
            ],
        ),
    ]
