# Generated by Django 5.1.5 on 2025-04-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0048_packagemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicechild',
            name='suppid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.supplier'),
        ),
    ]
