# Generated by Django 5.1.5 on 2025-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0049_alter_invoicechild_suppid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
