# Generated by Django 5.1.5 on 2025-04-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0050_ippatientadmission_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischarge',
            name='accomadationtype',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='bedno',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='condition_on_discharge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='floorno',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='roomno',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdviceOnDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField()),
                ('discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='ayurvedaapp.patientdischarge')),
            ],
        ),
        migrations.CreateModel(
            name='DischargeMedicationProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_medication', models.TextField(blank=True, null=True)),
                ('treatment_procedure', models.TextField(blank=True, null=True)),
                ('discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_procedures', to='ayurvedaapp.patientdischarge')),
            ],
        ),
    ]
