# Generated by Django 5.1.5 on 2025-05-05 11:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0052_ippatientadmission_advance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bystander_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ayurvedaapp.ippatientadmission')),
                ('mr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.packagemaster')),
            ],
        ),
    ]
