# Generated by Django 5.2.1 on 2025-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0054_ippatientroombooking_admissionenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientroombooking',
            name='bookingcancel',
            field=models.BooleanField(default=False),
        ),
    ]
