# Generated by Django 5.2.1 on 2025-05-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0055_ippatientroombooking_bookingcancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardname', models.CharField(default=None, max_length=400)),
                ('color', models.CharField(default=None, max_length=20)),
                ('linkname', models.CharField(default=None, max_length=400)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='dashboardallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=None, max_length=400)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('roleid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.role')),
                ('dashboardid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.dashboardesign')),
            ],
        ),
    ]
