# Generated by Django 5.2.1 on 2025-05-23 05:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0056_dashboardesign_dashboardallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='advancedue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='amountpaidwithoutbystander',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='originalpcktotaalamountpaid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='payingamount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='ippatientadmission',
            name='totalpackageamountwithoutdiscount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='IPPackageextend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_extendepackageamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dueofextend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amountpaidonextend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.ippatientadmission')),
                ('mr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.packagemaster')),
            ],
        ),
    ]
