# Generated by Django 5.2.1 on 2025-06-16 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0058_treatmentroom_details_oppatienttreamentroombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='oppatienttreamentroombooking',
            name='bookingenddate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
