# Generated by Django 5.2.4 on 2025-07-05 11:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0060_proceduredt_oppatienttimeslotbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='oppatientadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.TextField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('Current_Date', models.DateField(default=datetime.date.today)),
                ('age', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reasonforadmission', models.TextField(blank=True, default=None, null=True)),
                ('Admittedstatus', models.BooleanField(default=True)),
                ('need_package', models.BooleanField(default=False)),
                ('total_package_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('need_bystander', models.BooleanField(default=False)),
                ('bystander_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalpaidamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payingamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amountpaidwithoutbystander', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('advancedue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('originalpcktotaalamountpaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalpackageamountwithoutdiscount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MR_Number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.packagemaster')),
            ],
        ),
        migrations.CreateModel(
            name='OPPackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bystander_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.packagemaster')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ayurvedaapp.oppatientadmission')),
            ],
        ),
    ]
