# Generated by Django 5.1.4 on 2025-07-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0061_oppatientadmission_oppackagepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch'),
        ),
    ]
