# Generated by Django 5.1.4 on 2025-07-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0062_followup_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatientadmission',
            name='admittedbranch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch'),
        ),
    ]
