# Generated by Django 5.2.4 on 2025-08-29 11:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0064_physicalstockdetails_stockbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='labtestchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('testname', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='labtestmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clairvedacasehistory',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='clairvedacasehistory',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='clairvedacasehistory',
            name='drug_history',
        ),
        migrations.RemoveField(
            model_name='clairvedacasehistory',
            name='test_needed',
        ),
        migrations.CreateModel(
            name='casehistorydietplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('noofdays', models.CharField(blank=True, max_length=100, null=True)),
                ('foodtobeavoided', models.TextField(blank=True, null=True)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casehistdietplan', to='ayurvedaapp.clairvedacasehistory')),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.diet')),
                ('handledbystaff', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='casehistorydoctorsnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorsnote', to='ayurvedaapp.clairvedacasehistory')),
                ('handledbystaff', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='casehistorymedicalandsurgicalhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalhistory', models.TextField(blank=True)),
                ('surgicalhist', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casehistory', to='ayurvedaapp.clairvedacasehistory')),
                ('handledbystaff', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='casehistorytreatmentplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casetreatmntplan', to='ayurvedaapp.clairvedacasehistory')),
                ('prepairedby', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trmntplan', to='ayurvedaapp.treatment_master')),
            ],
        ),
        migrations.CreateModel(
            name='casehistryvitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('height', models.FloatField(blank=True, default=0.0, null=True)),
                ('bmi', models.FloatField(blank=True, default=0.0, null=True)),
                ('bp', models.CharField(blank=True, max_length=20, null=True)),
                ('fbs', models.FloatField(blank=True, default=0.0, null=True)),
                ('ppbs', models.FloatField(blank=True, default=0.0, null=True)),
                ('hba1c', models.FloatField(blank=True, default=0.0, null=True)),
                ('tchol', models.FloatField(blank=True, default=0.0, null=True)),
                ('hdl', models.FloatField(blank=True, default=0.0, null=True)),
                ('tg', models.FloatField(blank=True, default=0.0, null=True)),
                ('ldl', models.FloatField(blank=True, default=0.0, null=True)),
                ('s_creatinine', models.FloatField(blank=True, default=0.0, null=True)),
                ('uric_acid', models.FloatField(blank=True, default=0.0, null=True)),
                ('sgpt', models.FloatField(blank=True, default=0.0, null=True)),
                ('sgot', models.FloatField(blank=True, default=0.0, null=True)),
                ('alcohol', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
            ],
        ),
        migrations.CreateModel(
            name='casehistorylabtestrequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casehistlabtest', to='ayurvedaapp.clairvedacasehistory')),
                ('handledbystaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('labtestchild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labtestchild')),
            ],
        ),
        migrations.CreateModel(
            name='casehistorylabresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=200, null=True)),
                ('normal_value', models.CharField(blank=True, max_length=200, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labresult', to='ayurvedaapp.patient_details')),
                ('preparedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
                ('labtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labtestchild')),
            ],
        ),
        migrations.AddField(
            model_name='labtestchild',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labtestmaster'),
        ),
        migrations.CreateModel(
            name='Prescriptionnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptiondate', models.DateField(default=datetime.date.today)),
                ('medicine_name', models.CharField(max_length=100)),
                ('moringtime', models.CharField(max_length=100)),
                ('noontime', models.CharField(max_length=100)),
                ('nighttime', models.CharField(max_length=100)),
                ('beforeorafterdiet', models.CharField(max_length=100)),
                ('medicineguideline', models.CharField(max_length=400)),
                ('noofdays', models.CharField(blank=True, max_length=400, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('case_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionnew', to='ayurvedaapp.clairvedacasehistory')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionnew', to='ayurvedaapp.clairvedafollowup')),
                ('patient', models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='ptid', to='ayurvedaapp.patient_details')),
                ('physicalstock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.physicalstockdetails')),
                ('prescribeddoctor', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
