# Generated by Django 5.1.4 on 2025-08-30 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0065_labtestchild_labtestmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistorydietplan',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
        migrations.AddField(
            model_name='casehistorydoctorsnote',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
        migrations.AddField(
            model_name='casehistorylabtestrequisition',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
        migrations.AddField(
            model_name='casehistorymedicalandsurgicalhistory',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
        migrations.AddField(
            model_name='casehistorytreatmentplan',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
        migrations.AddField(
            model_name='casehistryvitals',
            name='handledbystaff',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails'),
        ),
        migrations.AddField(
            model_name='clairvedacasehistory',
            name='branchcasehstry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch'),
        ),
        migrations.AlterField(
            model_name='casehistorylabresult',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
        migrations.AlterField(
            model_name='prescriptionnew',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptid', to='ayurvedaapp.patient_details'),
        ),
    ]
