# Generated by Django 5.2.4 on 2025-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0066_casehistorydietplan_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gstno',
            field=models.CharField(default='none', max_length=500, null=True),
        ),
    ]
