# Generated by Django 5.2.4 on 2025-08-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0067_branch_gstno'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionnew',
            name='qtyprescriped',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
