# Generated by Django 5.2.4 on 2025-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0071_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentinvoicemaster',
            name='payementmode',
            field=models.CharField(blank=True, default='Cash', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='payementmode',
            field=models.CharField(blank=True, default='Cash', max_length=300, null=True),
        ),
    ]
