# Generated by Django 5.1.3 on 2025-09-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0074_casehistorylabresult_labtestdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechild',
            name='cgstamount',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='sgstamount',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicechild',
            name='taxableamount',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='totalcgstamount',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='totalsgstamount',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='totaltaxableamount',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
