# Generated by Django 5.2.4 on 2025-09-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0075_invoicechild_cgstamount_invoicechild_sgstamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hosporclinic',
            field=models.CharField(default='none', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Branch_Address',
            field=models.CharField(max_length=500),
        ),
    ]
