# Generated by Django 5.2.4 on 2025-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0077_branch_compositiontax_alter_branch_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemaster',
            name='card_amount',
            field=models.CharField(blank=True, default=0, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='cash_amount',
            field=models.CharField(blank=True, default=0, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='gpay_amount',
            field=models.CharField(blank=True, default=0, max_length=400, null=True),
        ),
    ]
