# Generated by Django 5.2.4 on 2025-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0078_invoicemaster_card_amount_invoicemaster_cash_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemaster',
            name='shipping',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemaster',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemaster',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemaster',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
