# Generated by Django 5.2.4 on 2025-09-26 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0079_alter_invoicemaster_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newInvoiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payementmode', models.CharField(blank=True, default='Cash', max_length=300, null=True)),
                ('Invoicenumber', models.CharField(default=None, max_length=400)),
                ('currentdate', models.DateField()),
                ('subtotal', models.FloatField(blank=True, default=0, null=True)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('shipping', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('patientname', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('patientphno', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('discount', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('consultationfee', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('consultationfeecumregfee', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('restockstatus', models.BooleanField(default=True)),
                ('totalsgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('totalcgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('totaltaxableamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cash_amount', models.CharField(blank=True, default=0, max_length=400, null=True)),
                ('gpay_amount', models.CharField(blank=True, default=0, max_length=400, null=True)),
                ('card_amount', models.CharField(blank=True, default=0, max_length=400, null=True)),
                ('Mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('hospitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.hospitaldetails')),
                ('preparedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
            ],
        ),
        migrations.CreateModel(
            name='newInvoiceChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('particulars', models.CharField(default=None, max_length=400)),
                ('amount', models.FloatField()),
                ('sutotal', models.FloatField()),
                ('currentdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoiceno', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=400)),
                ('patientname', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('patientphno', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('batchno', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('expirydate', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('mfg', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('unt', models.CharField(default=None, max_length=400)),
                ('hsncode', models.CharField(default=None, max_length=400)),
                ('tax', models.FloatField(default=None)),
                ('taxamount', models.FloatField(default=None)),
                ('baseqty', models.CharField(default=None, max_length=400)),
                ('sgst', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cgst', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('sgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('taxableamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('suppid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.supplier')),
                ('invmasterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.newinvoicemaster')),
            ],
        ),
    ]
