# Generated by Django 5.2.4 on 2025-09-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0080_newinvoicemaster_newinvoicechild'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicinemaster_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=100, null=True)),
                ('itemnm', models.CharField(max_length=300)),
                ('Generic_name', models.CharField(default=None, max_length=300, null=True)),
                ('racknumber', models.CharField(default=None, max_length=300, null=True)),
                ('Sideeffect', models.CharField(default=None, max_length=300, null=True)),
                ('hsncode', models.CharField(default=None, max_length=300, null=True)),
                ('Subcategory_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.itemsubcategory')),
                ('bsuntid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.baseunit')),
                ('taxpercentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.taxmaster')),
            ],
        ),
        migrations.CreateModel(
            name='medicinemasterrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.CharField(default=None, max_length=300, null=True)),
                ('branchid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('itemid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.medicinemaster_new')),
            ],
        ),
    ]
