# Generated by Django 5.2.4 on 2025-10-21 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0081_medicinemaster_new_medicinemasterrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comapany_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='inventoryInvoiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payementmode', models.CharField(blank=True, default='Cash', max_length=300, null=True)),
                ('Invoicenumber', models.CharField(default=None, max_length=400)),
                ('currentdate', models.DateField()),
                ('subtotal', models.FloatField(blank=True, default=0, null=True)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('shipping', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('patientname', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('patientphno', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('discount', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('consultationfee', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('consultationfeecumregfee', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('restockstatus', models.BooleanField(default=True)),
                ('totalsgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('totalcgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('totaltaxableamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cash_amount', models.CharField(blank=True, default=0, max_length=400, null=True)),
                ('gpay_amount', models.CharField(blank=True, default=0, max_length=400, null=True)),
                ('card_amount', models.CharField(blank=True, default=0, max_length=400, null=True)),
                ('Mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('hospitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.hospitaldetails')),
                ('preparedby', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
            ],
        ),
        migrations.CreateModel(
            name='inventoryinvoicechild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('particulars', models.CharField(default=None, max_length=400)),
                ('amount', models.FloatField()),
                ('sutotal', models.FloatField()),
                ('currentdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoiceno', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=400)),
                ('patientname', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('patientphno', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('batchno', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('expirydate', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('mfg', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('unt', models.CharField(default=None, max_length=400)),
                ('hsncode', models.CharField(default=None, max_length=400)),
                ('tax', models.FloatField(default=None)),
                ('taxamount', models.FloatField(default=None)),
                ('baseqty', models.CharField(default=None, max_length=400)),
                ('sgst', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cgst', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('sgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('cgstamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('taxableamount', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Mrno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
                ('suppid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.supplier')),
                ('invmasterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.inventoryinvoicemaster')),
            ],
        ),
        migrations.CreateModel(
            name='inventorymaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=100, null=True)),
                ('itemnm', models.CharField(max_length=300)),
                ('Generic_name', models.CharField(default=None, max_length=300, null=True)),
                ('racknumber', models.CharField(default=None, max_length=300, null=True)),
                ('Sideeffect', models.CharField(default=None, max_length=300, null=True)),
                ('hsncode', models.CharField(default=None, max_length=300, null=True)),
                ('bsuntid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.baseunit')),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.inventorycategory')),
                ('taxpercentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.taxmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Inventorystockdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer_date', models.DateField(null=True)),
                ('Expiry_date', models.DateField(null=True)),
                ('Batch_no', models.CharField(default=None, max_length=500)),
                ('Rate', models.CharField(default=None, max_length=300)),
                ('qty', models.IntegerField()),
                ('lastupdatedate', models.DateField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('Comapany_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.inventorycompany')),
                ('insertedstaffid', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('itemnm', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.inventorymaster')),
                ('stockbranch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('storenm', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.storedetails')),
                ('suppliernm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.supplier')),
                ('unt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.unitdt')),
            ],
        ),
        migrations.CreateModel(
            name='invreorderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(default=None, max_length=300)),
                ('companyid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.inventorycompany')),
                ('itemname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.inventorymaster')),
            ],
        ),
    ]
