# Generated by Django 5.1.3 on 2025-10-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0082_inventorycategory_inventorycompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionnew',
            name='case_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionnew', to='ayurvedaapp.clairvedacasehistory'),
        ),
    ]
