# Generated by Django 5.1.3 on 2025-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0085_alter_casehistorylabtestrequisition_case_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentinvoicemaster',
            name='paymentmode',
            field=models.CharField(blank=True, default='Cash', max_length=300, null=True),
        ),
    ]
