# Generated by Django 5.2.4 on 2025-11-12 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0086_treatmentinvoicemaster_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditnote_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('creditnote_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, default=0, null=True)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('patientname', models.CharField(blank=True, max_length=400, null=True)),
                ('patientphno', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffallocation')),
                ('hospitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.hospitaldetails')),
                ('invoicemaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='ayurvedaapp.newinvoicemaster')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNoteChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(blank=True, max_length=400, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('restocked', models.BooleanField(default=False)),
                ('invoice_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.newinvoicechild')),
                ('creditnote_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_items', to='ayurvedaapp.creditnotemaster')),
            ],
        ),
    ]
