# Generated by Django 5.1.3 on 2025-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0087_creditnotemaster_creditnotechild'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
