# Generated by Django 5.2.4 on 2025-12-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0091_newinvoicechild_manufacturedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_payment_mode', models.CharField(max_length=300)),
                ('updated_payment_mode', models.CharField(max_length=300)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('updatedamount', models.FloatField(default=0)),
                ('beforeupdatingamount', models.FloatField(default=0)),
                ('appointment_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.appointmentinvoicemaster')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffallocation')),
            ],
        ),
    ]
