# Generated by Django 5.2.4 on 2025-12-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0094_stockauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentupdatelog',
            name='previous_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentupdatelog',
            name='updated_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
