# Generated by Django 5.2.4 on 2026-01-07 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0096_paymentupdatelognew'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('original_token_no', models.CharField(blank=True, max_length=300, null=True)),
                ('original_doctor_id', models.IntegerField(blank=True, null=True)),
                ('original_appointment_date', models.DateField(blank=True, null=True)),
                ('original_status', models.CharField(blank=True, max_length=100, null=True)),
                ('original_contactno', models.CharField(blank=True, max_length=100, null=True)),
                ('original_remark', models.CharField(blank=True, max_length=300, null=True)),
                ('original_fee', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('new_doctor_id', models.IntegerField(blank=True, null=True)),
                ('new_appointment_date', models.DateField(blank=True, null=True)),
                ('new_status', models.CharField(blank=True, max_length=100, null=True)),
                ('new_contactno', models.CharField(blank=True, max_length=100, null=True)),
                ('new_remark', models.CharField(blank=True, max_length=300, null=True)),
                ('new_fee', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('action_date', models.DateField(default=django.utils.timezone.now)),
                ('action_time', models.TimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.appointments')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
            ],
        ),
    ]
