# Generated by Django 5.2.4 on 2026-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0098_zohoaccesstoken_zohoconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientauditlog',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientauditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientauditlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientauditlog',
            name='mrno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
