# Generated by Django 6.0 on 2026-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0099_patientauditlog_field_name_patientauditlog_new_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='visit_duration',
            field=models.IntegerField(default=30, verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='visit_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Visit End Time'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='visit_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Visit Start Time'),
        ),
    ]
