# Generated by Django 6.0 on 2026-02-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0100_appointments_visit_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('schedule_date', models.DateField(blank=True, null=True, verbose_name='Schedule date for case history')),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Prescription created')),
                ('used_date', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.appointments', verbose_name='Linked Appointment')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_appointments', to='ayurvedaapp.staffdetails')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details')),
            ],
            options={
                'verbose_name': 'Assigned Appointment',
                'verbose_name_plural': 'Assigned Appointments',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
