# Generated by Django 6.0 on 2026-03-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0102_prescriptioneditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Followup', 'Followup'), ('Revisit', 'Revisit')], max_length=50)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.staffdetails')),
            ],
            options={
                'ordering': ['branch', 'doctor', 'visit_type'],
                'unique_together': {('branch', 'doctor', 'visit_type')},
            },
        ),
    ]
