# Generated by Django 6.0 on 2026-03-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0104_casehistorylabbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistorylabresult',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.casehistorylabbill'),
        ),
    ]
