# Generated by Django 5.2.5 on 2026-03-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0106_alter_appointmentfee_visit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_address', models.TextField()),
                ('buyer_gstin', models.CharField(blank=True, max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=255)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('po_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_address', models.TextField()),
                ('proforma_reference', models.CharField(blank=True, max_length=50)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(max_length=50)),
                ('transport_mode', models.CharField(blank=True, max_length=100)),
                ('gst_applicable', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=255)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('approver_designation', models.CharField(blank=True, max_length=100)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('batch_info', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=4)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ayurvedaapp.proformainvoice')),
            ],
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ayurvedaapp.purchaseorder')),
            ],
        ),
    ]
