# Generated by Django 5.2.5 on 2026-03-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0108_alter_purchaseorder_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.branch'),
        ),
        migrations.AlterField(
            model_name='stockauditlog',
            name='action',
            field=models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('RESTORE', 'Restore'), ('SALE', 'Sale')], max_length=10),
        ),
    ]
