# Generated by Django 5.2.5 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0109_proformainvoice_branch_purchaseorder_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
