# Generated by Django 5.2.5 on 2026-03-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0110_proformainvoice_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='payment_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails'),
        ),
    ]
