# Generated by Django 5.2.5 on 2026-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0111_alter_proformainvoice_payment_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='proforma_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
