# Generated by Django 5.2.5 on 2026-03-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0112_alter_purchaseorder_proforma_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenumber', models.CharField(default=None, max_length=400)),
                ('invoice_date', models.DateField()),
                ('proforma_reference', models.CharField(blank=True, max_length=400, null=True)),
                ('buyer_name', models.CharField(max_length=400)),
                ('buyer_address', models.TextField()),
                ('buyer_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('consignee_name', models.CharField(max_length=400)),
                ('consignee_address', models.TextField()),
                ('consignee_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=255)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('hospitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.hospitaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='B2BInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('batch_info', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=4)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ayurvedaapp.b2binvoice')),
            ],
        ),
        migrations.CreateModel(
            name='B2CInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenumber', models.CharField(default=None, max_length=400)),
                ('invoice_date', models.DateField()),
                ('proforma_reference', models.CharField(blank=True, max_length=400, null=True)),
                ('customer_name', models.CharField(max_length=400)),
                ('customer_address', models.TextField()),
                ('customer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=255)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch')),
                ('hospitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.hospitaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='B2CInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('batch_info', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=4)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ayurvedaapp.b2cinvoice')),
            ],
        ),
    ]
