# Generated by Django 5.2.5 on 2026-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0114_b2binvoice_buyer_state_b2binvoice_buyer_state_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Credit', 'Credit')], default='Unpaid', max_length=10),
        ),
    ]
