# Generated by Django 5.1.4 on 2026-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0117_purchaseorder_destination_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_franchise',
            field=models.BooleanField(default=False),
        ),
    ]
