# Generated by Django 5.1.4 on 2026-03-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0119_stocktransfer_stocktransferitem_stocktransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockauditlog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
