# Generated by Django 5.2.5 on 2026-04-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0120_stockauditlog_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.purchaseorder'),
        ),
    ]
