# Generated by Django 5.2.5 on 2026-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0121_proformainvoice_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnchild',
            name='purchase_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
