# Generated by Django 5.2.5 on 2026-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0122_grnchild_purchase_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstockdetails',
            name='purchase_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
