# Generated by Django 5.2.8 on 2026-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0124_labtestmaster_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestchild',
            name='rate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
