# Generated by Django 5.2.8 on 2026-06-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0126_labunitmaster_labinvoicemaster_labinvoicechild_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='header/')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='footer/')),
            ],
        ),
    ]
