# Generated by Django 5.2.8 on 2026-06-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0129_proceduremaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremaster',
            name='branch_id',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.branch'),
        ),
    ]
