# Generated by Django 5.2.8 on 2026-06-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0131_casualityinvoicemaster_casualityinvoicechild'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvoicemaster',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_casuality_invoices', to='ayurvedaapp.staffallocation'),
        ),
        migrations.AddField(
            model_name='labinvoicemaster',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
