# Generated by Django 5.2.8 on 2026-06-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0132_labinvoicemaster_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistorylabresult',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labinvoicemaster'),
        ),
    ]
