# Generated by Django 5.2.8 on 2026-06-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0133_alter_casehistorylabresult_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistorylabtestrequisition',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labinvoicemaster'),
        ),
    ]
