# Generated by Django 5.2.8 on 2026-06-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0134_casehistorylabtestrequisition_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistorylabtestrequisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
