# Generated by Django 5.2.8 on 2026-06-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0135_alter_casehistorylabtestrequisition_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvoicemaster',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.patient_details'),
        ),
    ]
