# Generated by Django 5.2.8 on 2026-06-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0137_labrequisitionmaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labinvoicemaster',
            name='patient_mr',
        ),
        migrations.RemoveField(
            model_name='labinvoicemaster',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='labinvoicemaster',
            name='patient_phone',
        ),
    ]
