# Generated by Django 5.2.8 on 2026-06-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0139_labresultmaster_casehistorylabresult_result_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvoicechild',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labtestchild'),
        ),
    ]
