# Generated by Django 5.2.11 on 2026-06-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0143_physicalstockdetails_wholesale_rate_purchaseinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
