# Generated by Django 5.2.11 on 2026-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0147_newinvoicemaster_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvoicemaster',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
