# Generated by Django 5.2.11 on 2026-06-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0148_alter_newinvoicemaster_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='manufacturer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
