# Generated by Django 5.2.11 on 2026-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0149_purchaseinvoiceitem_manufacturer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
