# Generated by Django 5.2.11 on 2026-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0150_purchaseinvoice_amount_in_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ippackagepayment',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='ippackagepayment',
            name='mr_number',
        ),
        migrations.RemoveField(
            model_name='ippackagepayment',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='advancedue',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='amountpaidwithoutbystander',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='bystander_rate',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='need_bystander',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='need_package',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='originalpcktotaalamountpaid',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='package',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='payingamount',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='total_package_rate',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='totalpackageamountwithoutdiscount',
        ),
        migrations.RemoveField(
            model_name='ippatientadmission',
            name='totalpaidamount',
        ),
        migrations.DeleteModel(
            name='IPPackageextend',
        ),
        migrations.DeleteModel(
            name='IPPackagePayment',
        ),
    ]
