# Generated by Django 5.2.11 on 2026-06-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0152_ippatientadmission_ipnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
