# Generated by Django 5.2.11 on 2026-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0154_physicalstockdetails_base_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstockdetails',
            name='total_base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='total_base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
