# Generated by Django 5.2.11 on 2026-06-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0155_physicalstockdetails_total_base_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='unt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.unitdt'),
        ),
    ]
