# Generated by Django 5.2.11 on 2026-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0156_purchaseinvoiceitem_unt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstockdetails',
            name='total_base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='total_base_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
