# Generated by Django 5.2.11 on 2026-06-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0157_alter_physicalstockdetails_total_base_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_time_of_birth', models.DateTimeField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('file_location', models.TextField(blank=True, null=True)),
                ('is_new_born', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='birth_reg_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_registrations', to='ayurvedaapp.patient_details')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeathRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unregistered_name', models.CharField(blank=True, max_length=300, null=True)),
                ('unregistered_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('unregistered_age', models.CharField(blank=True, max_length=20, null=True)),
                ('unregistered_address', models.TextField(blank=True, null=True)),
                ('unregistered_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_datetime', models.DateTimeField(blank=True, null=True)),
                ('death_datetime', models.DateTimeField(blank=True, null=True)),
                ('consulting_doctor', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('booking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('citizen_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uhid_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('corporate_company', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('privileged_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='death_reg_photos/')),
                ('registration_type', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffdetails')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='death_registrations', to='ayurvedaapp.patient_details')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
