# Generated by Django 5.2.11 on 2026-06-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0159_birthregister_child_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregister',
            name='child_op',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deathregister',
            name='consulting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ayurvedaapp.staffallocation'),
        ),
    ]
