# Generated by Django 5.2.11 on 2026-07-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0161_casehistorylabtestrequisition_labtestgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='labinvoicechild',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedaapp.labtestmaster'),
        ),
    ]
