# Generated by Django 5.2.11 on 2026-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0162_labinvoicechild_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistorytreatmentplan',
            name='deletedstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipexpandedbillotherexpensesdetail',
            name='deletedstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionnew',
            name='deletedstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_details',
            name='nursing_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room_details',
            name='water_electricity_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
