# Generated by Django 5.2.11 on 2026-07-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0165_asset_assetauditlog_assettransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettransfer',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='assettransfer',
            name='ayurvedaapp_transfe_4e0603_idx',
        ),
        migrations.RemoveIndex(
            model_name='assettransfer',
            name='ayurvedaapp_asset_i_0b1b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='assettransfer',
            name='ayurvedaapp_from_br_c60472_idx',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='to_branch',
        ),
    ]
