# Generated by Django 5.2.11 on 2026-07-09 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedaapp', '0166_alter_assettransfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Branch', to='ayurvedaapp.branch'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_from', to='ayurvedaapp.department'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_to', to='ayurvedaapp.department'),
        ),
    ]
